# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08dfa110cfe4bea1f51bd3815c27155b"
application_url = "https://example.com"
embedded = true
name = "delivery-customizations"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_delivery_customizations"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
