# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08dfa110cfe4bea1f51bd3815c27155b"
name = "delivery-customizations"
application_url = "https://shopify-app.gameology.com.au"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_products"

[auth]
redirect_urls = [ "https://shopify-app.gameology.com.au/api/auth" ]
